baseURL = "https://example.com/"
languageCode = "en-us"
title = "A Hugo theme for creating Reveal.js presentations"
disableKinds = ["sitemap", "RSS"]

[author]
name = "Josh Dzielak"

[params]
description = "Includes a handy markdown-based syntax and shortcodes to help you get presentations done fast"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
